### ISSUE TITLE
Read layer settings from layer.yaml, instead of having a separate YAML file

### ISSUE THREAD

**Issue by nottrobin** [canonical-webteam/layer-untar-resources#2]
As mentioned in https://github.com/canonical-webteam/charm-wsgi-app/issues/1:

> I would prefer just adding to the options section of layer.yaml rather than the additional untar-resources.yaml file, something like what the apt later does https://git.launchpad.net/layer-apt/tree/README.md#n169

**Comment by codersquid** [comment]
Could we have options in a nested dictionary? Like so,

```
  resources:
    my-resource:
      user: me
      destination: /path/to/my-resource
    my-other-resource:
      user: me
      destination: /path/to/third-party
```

You don't need the filename since charmtools will handle that for you.
